### ISSUE TITLE
Help with steam OS

### ISSUE THREAD

**Issue by AptGetGnome** [instantepiphany/steamdlfilter#3]
Not really a problem with Steamdlfilter, but is there anyway to install steamdlfilter on steam os? its hard to build from source when most of the build essentials are stopped by the already installed steam dependencies, but if steamdlfilter was in a repository i would be able to install it. Anything you can think of to work around this issue?

**Comment by instantepiphany** [comment]
Hey adamsarin, I don't know why I didn't spot the email for this. Is steamdlfilter still something you would like to get running? If so, I can give you a hand getting it running on SteamOS. From memory, SteamOS is just Ubuntu modified to run Steam in Big Picture mode from boot (with drivers for some GPUs preinstalled I think and maybe other magic). It shouldn't be hard to switch to a terminal, compile the library, and replace whatever script launches the steam binary, with my script that inserts steamdlfilter. Reopen this issue if you still want a hand, a year later!
